[package]
name = "pixel_bender"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }
num-traits = { workspace = true }
num-derive = { workspace = true }
byteorder = { workspace = true }
