[package]
name = "pbasm"
description = "pbasm: The Last PixelBender (Assembler)"
authors = ["Kamil Jarosz <kjarosh256@gmail.com>"]
version = "0.1.0"
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
clap = { workspace = true }
anyhow = { workspace = true }
ruffle_render = { path = "..", features = ["assembly"] }
