name: Check Size

on:
  pull_request:
    branches: [master-sync]

jobs:
  check-size:
    name: Check Size ${{ matrix.type }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - ref: ${{ github.base_ref }}
            type: Before
          - ref: ${{ github.head_ref }}
            type: After
    runs-on: ubuntu-24.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.ref }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt install -y libasound2-dev libxcb-shape0-dev libxcb-xfixes0-dev libgtk-3-dev mesa-vulkan-drivers libpango1.0-dev libudev-dev

      - name: Build desktop
        run: cargo build --locked --package ruffle_desktop --release --features jpegxr

      - name: Build web
        env:
          CARGO_FEATURES: jpegxr
        working-directory: web
        run: |
          npm ci
          npm run build:dual-wasm-repro

      - name: Record sizes
        run: |
          size_desktop=$(stat --printf="%s" target/release/ruffle_desktop)
          size_web=$(du -bs web/packages/selfhosted/dist | cut -f 1 -d $'\t')
          echo "size_${{ matrix.type }}_desktop=$size_desktop" >> $GITHUB_OUTPUT
          echo "size_${{ matrix.type }}_web=$size_web" >> $GITHUB_OUTPUT

  print_sizes:
    name: Print sizes
    needs: [check-size]
    runs-on: ubuntu-24.04
    steps:
      - name: Print sizes
        run: |
          echo Desktop: ${{ needs.check-size.outputs.size_Before_desktop }} -> ${{ needs.check-size.outputs.size_After_desktop }}
          echo Web: ${{ needs.check-size.outputs.size_Before_web }} -> ${{ needs.check-size.outputs.size_After_web }}
