name: Upload source texts to Crowdin

on:
  push:
    branches: [ metainfo-locale ]
  workflow_dispatch:

jobs:
  crowdin:
    runs-on: ubuntu-latest

    if: github.repository == 'kjarosh/ruffle'

    steps:
      - name: Install dependencies
        run: sudo apt-get install -y appstream gettext itstool

      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare metainfo translations
        working-directory: desktop/packages/linux
        run: |
          mkdir -p locale
          itstool -i /usr/share/gettext/its/metainfo.its -o locale/rs.ruffle.Ruffle.metainfo.xml.pot rs.ruffle.Ruffle.metainfo.xml

      - name: Crowdin push
        uses: crowdin/github-action@v2
        with:
          config: 'crowdin.yml'
          upload_sources: true
          upload_translations: false
          download_translations: false
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
